# Generated by Django 6.0 on 2025-12-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('api_source', models.CharField(choices=[('TBA', 'The Blue Alliance'), ('FIRST', 'FIRST API')], default='TBA', max_length=20)),
                ('auto_rotation_enabled', models.BooleanField(default=False)),
                ('rotation_interval', models.IntegerField(default=5, help_text='Number of matches before rotating scouters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('epa', models.FloatField(blank=True, help_text='Expected Points Added', null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('last_metrics_update', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
            ],
            options={
                'ordering': ['team_number'],
                'unique_together': {('team_number', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('match_type', models.CharField(choices=[('QUAL', 'Qualification'), ('PLAYOFF', 'Playoff')], default='QUAL', max_length=10)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ALL_SUBMITTED', 'All Data Submitted')], default='UPCOMING', max_length=20)),
                ('red_score', models.IntegerField(blank=True, null=True)),
                ('blue_score', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('TIE', 'Tie')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='events.event')),
                ('blue_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue1_matches', to='events.team')),
                ('blue_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue2_matches', to='events.team')),
                ('blue_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue3_matches', to='events.team')),
                ('red_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red1_matches', to='events.team')),
                ('red_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red2_matches', to='events.team')),
                ('red_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red3_matches', to='events.team')),
            ],
            options={
                'ordering': ['scheduled_time', 'match_number'],
                'unique_together': {('event', 'match_number', 'match_type')},
            },
        ),
    ]
