# Generated by Django 6.0 on 2025-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(blank=True, help_text='Event type code from TBA', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_string',
            field=models.CharField(blank=True, help_text="Event type (e.g., 'Regional', 'District')", max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='tba_event_key',
            field=models.CharField(blank=True, help_text="TBA event key (e.g., '2024casj')", max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='week',
            field=models.IntegerField(blank=True, help_text='Competition week number', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='actual_time',
            field=models.DateTimeField(blank=True, help_text='Actual match start time', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='comp_level',
            field=models.CharField(blank=True, help_text='Competition level: qm, qf, sf, f', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='predicted_time',
            field=models.DateTimeField(blank=True, help_text='TBA predicted start time', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='set_number',
            field=models.IntegerField(default=1, help_text='Set number for playoff matches'),
        ),
        migrations.AddField(
            model_name='match',
            name='tba_match_key',
            field=models.CharField(blank=True, help_text='TBA match key', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='nickname',
            field=models.CharField(blank=True, help_text='Team nickname from TBA', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='rookie_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='state_prov',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
