# Generated by Django 6.0 on 2025-12-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_type_event_event_type_string_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('event', 'match_number', 'match_type', 'comp_level', 'set_number')},
        ),
    ]
