# Generated by Django 6.0 on 2025-12-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAggregateStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_total_auto_points', models.IntegerField(default=0)),
                ('red_total_teleop_points', models.IntegerField(default=0)),
                ('red_total_endgame_points', models.IntegerField(default=0)),
                ('red_predicted_score', models.IntegerField(default=0)),
                ('blue_total_auto_points', models.IntegerField(default=0)),
                ('blue_total_teleop_points', models.IntegerField(default=0)),
                ('blue_total_endgame_points', models.IntegerField(default=0)),
                ('blue_predicted_score', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_stats', to='events.match')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAggregateStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_auto_game_pieces', models.FloatField(default=0.0)),
                ('avg_auto_points', models.FloatField(default=0.0)),
                ('auto_mobility_rate', models.FloatField(default=0.0)),
                ('avg_teleop_game_pieces', models.FloatField(default=0.0)),
                ('avg_defense_rating', models.FloatField(default=0.0)),
                ('avg_speed_rating', models.FloatField(default=0.0)),
                ('climb_success_rate', models.FloatField(default=0.0)),
                ('avg_endgame_points', models.FloatField(default=0.0)),
                ('avg_overall_rating', models.FloatField(default=0.0)),
                ('reliability_score', models.FloatField(default=0.0, help_text='Based on disable/foul rates')),
                ('matches_scouted', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_stats', to='events.team')),
            ],
            options={
                'ordering': ['-avg_overall_rating'],
            },
        ),
    ]
