# Generated by Django 6.0 on 2025-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamaggregatestats',
            name='statbotics_auto_epa',
            field=models.FloatField(blank=True, help_text='Auto EPA from Statbotics', null=True),
        ),
        migrations.AddField(
            model_name='teamaggregatestats',
            name='statbotics_endgame_epa',
            field=models.FloatField(blank=True, help_text='Endgame EPA from Statbotics', null=True),
        ),
        migrations.AddField(
            model_name='teamaggregatestats',
            name='statbotics_epa',
            field=models.FloatField(blank=True, help_text='Total EPA from Statbotics', null=True),
        ),
        migrations.AddField(
            model_name='teamaggregatestats',
            name='statbotics_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamaggregatestats',
            name='statbotics_rank',
            field=models.IntegerField(blank=True, help_text='Event rank from Statbotics', null=True),
        ),
        migrations.AddField(
            model_name='teamaggregatestats',
            name='statbotics_teleop_epa',
            field=models.FloatField(blank=True, help_text='Teleop EPA from Statbotics', null=True),
        ),
        migrations.AddField(
            model_name='teamaggregatestats',
            name='statbotics_win_rate',
            field=models.FloatField(blank=True, help_text='Win rate from Statbotics', null=True),
        ),
    ]
