# Generated by Django 6.0 on 2025-12-04 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScouterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('RED_1', 'Red Alliance Position 1'), ('RED_2', 'Red Alliance Position 2'), ('RED_3', 'Red Alliance Position 3'), ('BLUE_1', 'Blue Alliance Position 1'), ('BLUE_2', 'Blue Alliance Position 2'), ('BLUE_3', 'Blue Alliance Position 3')], max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.match')),
                ('scouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.team')),
            ],
            options={
                'ordering': ['match__scheduled_time', 'position'],
                'unique_together': {('match', 'position')},
            },
        ),
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_winner', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue')], max_length=10)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='events.match')),
                ('scouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scouter', 'match')},
            },
        ),
        migrations.CreateModel(
            name='ScoutingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_match_notes', models.TextField(blank=True)),
                ('robot_starting_position', models.CharField(blank=True, max_length=50)),
                ('auto_mobility', models.BooleanField(default=False)),
                ('auto_game_pieces_scored', models.IntegerField(default=0)),
                ('auto_game_pieces_missed', models.IntegerField(default=0)),
                ('auto_points_estimate', models.IntegerField(default=0)),
                ('auto_notes', models.TextField(blank=True)),
                ('teleop_game_pieces_scored', models.IntegerField(default=0)),
                ('teleop_game_pieces_missed', models.IntegerField(default=0)),
                ('teleop_defense_rating', models.IntegerField(default=0, help_text='0-5 scale')),
                ('teleop_speed_rating', models.IntegerField(default=0, help_text='0-5 scale')),
                ('teleop_notes', models.TextField(blank=True)),
                ('endgame_climb_attempted', models.BooleanField(default=False)),
                ('endgame_climb_success', models.BooleanField(default=False)),
                ('endgame_park', models.BooleanField(default=False)),
                ('endgame_points_estimate', models.IntegerField(default=0)),
                ('endgame_notes', models.TextField(blank=True)),
                ('robot_disabled', models.BooleanField(default=False)),
                ('robot_tippy', models.BooleanField(default=False)),
                ('fouls_committed', models.IntegerField(default=0)),
                ('overall_rating', models.IntegerField(default=0, help_text='0-10 scale')),
                ('post_match_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_offline', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scouting.scouterassignment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_reports', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_reports', to='events.match')),
                ('scouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_reports', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_reports', to='events.team')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('match', 'scouter', 'team')},
            },
        ),
    ]
