# Generated by Django 6.0 on 2025-12-04 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('STRATEGIST', 'Strategist'), ('SCOUTER', 'Scouter')], default='SCOUTER', max_length=20)),
                ('prediction_points', models.IntegerField(default=0)),
                ('experience_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('LEVEL', 'Level Up'), ('PREDICTION', 'Prediction Master'), ('REPORTS', 'Report Champion'), ('ACCURACY', 'Data Accuracy')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('level_achieved', models.IntegerField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
    ]
